version: "3"

services:

  mongodb:
    image: dockerhub.ir/mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: workflow_db
      TZ: "Asia/Tehran"
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: 12345qwer
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis
    restart: always
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
